apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: dolores-brain
    app.kubernetes.io/name: dolores-brain
  name: dolores-brain
  namespace: dolores-brain
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8003
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: dolores-brain
    app.kubernetes.io/name: dolores-brain
