apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: todo
data:
  # Storage backend: postgres for production multiuser
  STORAGE_BACKEND: "postgres"
  PORT: "5000"
  DEBUG: "0"
  APP_NAME: "ToDo & Notes"
  # OIDC / Authentik
  OIDC_ENABLED: "1"
  OIDC_ISSUER: "https://auth.navy.dalmura.cloud/application/o/todo/"
  OIDC_SCOPES: "openid profile email"