apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: todo
data:
  DATA_FILE: "/data/appdata.json"
  WAL_FILE: "/data/appdata.wal"
  BACKUP_COUNT: "10"
  PORT: "5000"
  DEBUG: "0"
  APP_NAME: "ToDo & Notes"
