apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo

resources:
  - config.yaml
  - secret.sealed.yaml
  - pvc-storage.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - network-policy-todo.yaml
  - network-policy-traefik-public-patch.yaml
