apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo

resources:
  - config.yaml
  - secret.sealed.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
