apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: todo
    app.kubernetes.io/name: todo
  name: todo
  namespace: todo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: todo
    app.kubernetes.io/name: todo
