kind: ConfigMap
apiVersion: v1
metadata:
  name: anubis-env
data:
  BIND: ":8080"
  TARGET: " "
  COOKIE_DOMAIN: "navy.dalmura.cloud"
  REDIRECT_DOMAINS: "auth.navy.dalmura.cloud"
  PUBLIC_URL: "https://anubis.navy.dalmura.cloud"
  POLICY_FNAME: "/data/cfg/botPolicy.yaml"
  SLOG_LEVEL: "INFO"
  XFF_STRIP_PRIVATE: "false"
