apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: anubis

resources:
  - config-env.yaml
  - config-policy.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - network-policy-anubis.yaml
