apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frigate

resources:
  - cm-proxy_trusted_headers.yaml
  - pvc-config.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
