apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forgejo

resources:
  - service-account.yaml
  - vault-dynamic-secret.yaml
  - external-secret.yaml
  - postgres.yaml
  - ingress.yaml
  - ingress-ssh.yaml
