global:
  enabled: true

injector:
  # Maybe later, using ESO for now
  enabled: false

server:
  ingress:
    enabled: false

ha:
  apiAddr: https://vault.navy.dalmura.cloud
  clusterAddr: https://cluster.vault.navy.dalmura.cloud

ui:
  enabled: true
