---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ha-codeserver
  annotations:
    cert-manager.io/cluster-issuer: dalmura-letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: ha-code.indigo.dalmura.cloud
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: true
spec:
  ingressClassName: ingress-private
  tls:
    - hosts:
      - ha-code.indigo.dalmura.cloud
      secretName: home-assistant-code-cert
  rules:
  - host: ha-code.indigo.dalmura.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ha-codeserver
            port:
              name: codeserver
