apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: reactive-resume
    app.kubernetes.io/name: reactive-resume
  name: reactive-resume
  namespace: reactive-resume
spec:
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: reactive-resume
    app.kubernetes.io/name: reactive-resume
  type: ClusterIP
