---
grafana.ini:
  server:
    root_url: "https://grafana.indigo.dalmura.cloud"
    domain: "grafana.indigo.dalmura.cloud"

deploymentStrategy:
  type: Recreate

persistence:
  enabled: true
  size: 10Gi
  storageClassName: cluster-nobackup
