apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: emojirades

resources:
  - service-account.yaml
  - vault-dynamic-secret.yaml
  - external-secret.yaml
  - postgres.yaml
  - deployment.yaml
