#envFrom:
#  - # Do we need anything?

fullnameOverride: ha

ingress:
  # We manage this separately via overlays
  # Setting external just enables some ha config
  enabled: false
  external: true

persistence:
  enabled: true
  size: 10Gi
  storageClass: cluster-regular

securityContext:
  runAsUser: 0
  runAsGroup: 0

addons:
  codeserver:
    enabled: true
    ingress:
      # We manage this separately via overlays
      enabled: false
